name: dart_strapi
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.8

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  pedantic: ^1.8.0
  test: ^1.6.0
